# Generated by Django 6.1.1 on 2026-09-21 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_rename_stripe_customer_id_subscription_paddle_customer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='Время')),
                ('title', models.CharField(max_length=200, verbose_name='Дело')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Заметка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пункт расписания',
                'verbose_name_plural': 'Распорядок дня',
                'ordering': ['time'],
            },
        ),
    ]
