# Generated by Django 6.1.1 on 2026-09-22 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_scheduleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('expense', 'Расход'), ('income', 'Доход')], default='expense', max_length=10, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='Только для премиум'),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.category', verbose_name='Источник')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доход',
                'verbose_name_plural': 'Доходы',
                'ordering': ['-date'],
            },
        ),
    ]
